{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if (and $isDistributed (gt (int .Values.bloomPlanner.replicas) 0)) -}}
{{- include "loki.serviceAccount" (dict "target" "bloom-builder" "component" .Values.bloomBuilder "ctx" .) }}
{{- end -}}
