{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if $isDistributed }}
{{- include "loki.component" (dict "ctx" . "component" .Values.bloomBuilder "target" "bloom-builder") }}
{{- end }}
