{{- if .Values.tableManager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loki.tableManagerFullname" . }}
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "loki.tableManagerLabels" . | nindent 4 }}
  annotations:
    {{- with .Values.loki.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.tableManager.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.loki.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "loki.tableManagerSelectorLabels" . | nindent 6 }}
  template:
    {{- include "loki.podTemplate" (dict "target" "table-manager" "component" .Values.tableManager "ctx" .) | nindent 4 }}
{{- end }}
