changes:
  - version: 62
    deletions:
      - 'kms.sops'
    customFunctions:
      - sopsMigration
  - version: 63
    customFunctions:
      - removeIngressTracing
    deletions:
      - 'apps.istio.tracing'
      - 'apps.otel.otlpCollector'
      - 'apps.otel.resources.otlpCollector'
  - version: 64
    mutations:
      - apps.cnpg.useBackupPlugin: true
  - version: 65
    deletions:
      - 'apps.otel.resources.kubeRBACProxy'
  - version: 66
    additions:
      - 'apps.git-server.enabled': false
  - version: 67
    customFunctions:
      - removeIngressNginxValues
    deletions:
      - apps.istio.autoscaling.ingressgateway
      - apps.istio.resources.ingressgateway
  - version: 68
    deletions:
      - apps.loki.enableOpenTelemetry
  - version: 69
    deletions:
      - 'teamConfig.{team}.services[].auth'
      - 'teamConfig.{team}.services[].domain'
      - 'teamConfig.{team}.services[].forwardPath'
      - 'teamConfig.{team}.services[].hasCert'
      - 'teamConfig.{team}.services[].ownHost'
  - version: 70
    deletions:
      - 'teamConfig.{team}.password'
  - version: 71
    customFunctions:
      - preservePvcStorageClassInRawValues
  - version: 72
    customFunctions:
      - migrateGeneratedSecrets
    deletions:
      - apps.oauth2-proxy.config
      - apps.harbor.core
      - apps.harbor.jobservice
      - apps.harbor.registry.credentials.htpasswd
      - apps.harbor.registry.credentials.password
