{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if $isDistributed }}
{{- include "loki.hpa" (dict "target" "query-frontend" "component" .Values.queryFrontend "ctx" . "kind" "Deployment") }}
{{- end }}
