{{- $isSimpleScalable := eq (include "loki.deployment.isScalable" .) "true" -}}
{{- if $isSimpleScalable }}
{{- include "loki.pdb" (dict "target" "backend" "component" .Values.backend "ctx" .) }}
{{- end }}
