{{- $isSimpleScalable := eq (include "loki.deployment.isScalable" .) "true" -}}
{{- if and $isSimpleScalable (not .Values.read.legacyReadTarget ) }}
{{- include "loki.serviceAccount" (dict "target" "backend" "component" .Values.backend "ctx" .) }}
{{- end -}}
