{{- $isSimpleScalable := eq (include "loki.deployment.isScalable" .) "true" -}}
{{- if $isSimpleScalable }}
{{- include "loki.component" (dict "ctx" . "component" .Values.backend "target" "backend" "args" (list "-legacy-read-mode=false")) }}
{{- end }}
