nameOverride: ""
fullnameOverride: ""

defaultGatewayClass: "istio"
gateways: []
  # - name: platform
  #   listeners:
  #     - hostname: ""
  #       name: ""
  #       protocol: ""
  #       port: 0
  #       certificateRefs:
  #         - name: ""
  #       allowedRoutes:
  #         namespaces:
  #           from: All
  #   loadBalancerIP: null
  #   entrypoint: null
  #   serviceAnnotations: {}
  #   annotations: {}
