nameOverride: ""
fullnameOverride: ""

defaultGatewayClass: "istio"
gateways: []
  # - name: platform
  #   listeners:
  #     - hostname: ""
  #       certificateRefs:
  #         - name: ""
  #   loadBalancerIP: null
  #   entrypoint: null
  #   sourceIpAddressFiltering: []
  #   serviceAnnotations: {}
  #   annotations: {}
  #   namespaces:
  #     from: All
