annotations:
  artifacthub.io/changes: |
    - kind: added
      description: enhance openshift support (#1063)
    - kind: changed
      description: update lockfiles (#1065)
    - kind: changed
      description: update alpine/helm docker tag to v3.20.2 (#1064)
    - kind: changed
      description: update lockfiles (#1062)
    - kind: changed
      description: update lockfiles (#1061)
    - kind: changed
      description: update workflow dependencies (minor & patch) (#1060)
    - kind: fixed
      description: broken pipe in change-password help probe (#1052)
    - kind: changed
      description: update lockfiles (#1058)
    - kind: changed
      description: update lockfiles (#1057)
    - kind: changed
      description: update lockfiles (#1055)
    - kind: changed
      description: update lockfiles (#1054)
    - kind: changed
      description: update lockfiles (#1053)
    - kind: changed
      description: update lockfiles (#1050)
    - kind: changed
      description: update lockfiles (#1049)
    - kind: changed
      description: update lockfiles (#1048)
    - kind: changed
      description: remove myself from maintainers list (#1047)
    - kind: changed
      description: update commitlint/commitlint docker tag to v20.5.0 (#1046)
    - kind: changed
      description: update lockfiles (#1045)
    - kind: changed
      description: update workflow dependencies (minor & patch) (#1044)
    - kind: changed
      description: update dependency go-gitea/gitea to v1.25.5 (#1043)
    - kind: changed
      description: update lockfiles (#1040)
    - kind: changed
      description: update lockfiles (#1039)
    - kind: changed
      description: update workflow dependencies (minor & patch) (#1037)
    - kind: changed
      description: update lockfiles (#1036)
    - kind: changed
      description: update lockfiles (#1035)
    - kind: changed
      description: update lockfiles (#1033)
    - kind: changed
      description: update lockfiles (#1032)
    - kind: changed
      description: update lockfiles (#1031)
    - kind: changed
      description: update lockfiles (#1030)
    - kind: changed
      description: update commitlint/commitlint docker tag to v20.4.2 (#1029)
    - kind: changed
      description: update lockfiles (#1028)
    - kind: changed
      description: update lockfiles (#1026)
    - kind: changed
      description: update lockfiles (#1025)
    - kind: changed
      description: update https://github.com/aws-actions/configure-aws-credentials action to v6 (#1024)
    - kind: changed
      description: update commitlint/commitlint docker tag to v20.4.1 (#1021)
    - kind: changed
      description: update unittests/bash/test_helper/bats-mock digest to 9c239d6 (#1020)
    - kind: changed
      description: update lockfiles (#1019)
    - kind: changed
      description: update lockfiles (#1018)
    - kind: changed
      description: update commitlint/commitlint docker tag to v20.4.0 (#1017)
    - kind: changed
      description: update lockfiles (#1015)
    - kind: changed
      description: update workflow dependencies (minor & patch) (#1014)
    - kind: changed
      description: update bats testing framework (#1013)
    - kind: fixed
      description: 'suppress search domain queries for valkeys headless service [Close #972] (#982)'
    - kind: fixed
      description: add missing persistence configuration of valkey primary and replica
    - kind: changed
      description: add postgresql-ha.persistence.storageClass
    - kind: fixed
      description: add options to disable persistence of dependencies
  artifacthub.io/links: |
    - name: support
      url: https://gitea.com/gitea/helm-gitea/issues
apiVersion: v2
appVersion: 1.25.5
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.7.27
- condition: postgresql-ha.enabled
  name: postgresql-ha
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.3.2
- condition: valkey-cluster.enabled
  name: valkey-cluster
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 3.0.24
- condition: valkey.enabled
  name: valkey
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 3.0.31
description: Gitea Helm chart for Kubernetes
icon: https://gitea.com/assets/img/logo.svg
keywords:
- git
- issue tracker
- code review
- wiki
- gitea
- gogs
maintainers:
- email: markus.pesch+apps@cryptic.systems
  name: Markus Pesch
- email: dselen@nerthus.nl
  name: Daan Selen
- email: christopher.homberger@web.de
  name: Christopher Homberger
name: gitea
sources:
- https://gitea.com/gitea/helm-gitea
- https://github.com/go-gitea/gitea
- https://docker.gitea.com/gitea
type: application
version: 12.5.1
