annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: update https://github.com/crazy-max/ghaction-import-gpg action to v7 (#1038)
  artifacthub.io/links: |
    - name: support
      url: https://gitea.com/gitea/helm-gitea/issues
apiVersion: v2
appVersion: 1.25.5
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.7.27
- condition: postgresql-ha.enabled
  name: postgresql-ha
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.3.2
- condition: valkey-cluster.enabled
  name: valkey-cluster
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 3.0.24
- condition: valkey.enabled
  name: valkey
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 3.0.31
description: Gitea Helm chart for Kubernetes
icon: https://gitea.com/assets/img/logo.svg
keywords:
- git
- issue tracker
- code review
- wiki
- gitea
- gogs
maintainers:
- email: markus.pesch+apps@cryptic.systems
  name: Markus Pesch
- email: dselen@nerthus.nl
  name: Daan Selen
- email: christopher.homberger@web.de
  name: Christopher Homberger
name: gitea
sources:
- https://gitea.com/gitea/helm-gitea
- https://github.com/go-gitea/gitea
- https://docker.gitea.com/gitea
type: application
version: 12.5.3
