{
 "title": "Policy Violations",
 "description": "Visualize violations from OPA Gatekeeper and OPA Scorecard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Summaries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mutation request count",
   "type": "timeseries",
   "description": "Description: The number of requests that are routed to mutation webhook",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (mutation_status, pod) (rate(gatekeeper_mutation_request_count[20m]))",
     "legendFormat": "{{mutation_status}}"
    }
   ]
  },
  {
   "title": "Total Violations by kind",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (kind) (opa_scorecard_constraint_violations{violating_namespace=~\"$namespace\"})",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Scorecard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OPA Violations",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "group(opa_scorecard_constraint_violations{violating_namespace=~\"$namespace\"}) by (time, violating_kind, violating_namespace, violating_name, kind, violation_enforcement, violation_msg)"
    }
   ]
  },
  {
   "title": "OPA Violations Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (violating_name) (opa_scorecard_constraint_violations{violating_namespace=~\"$namespace\"})",
     "legendFormat": "{{violating_name}}"
    }
   ]
  }
 ]
}