{{- if eq (include "oauth2-proxy.alpha-config.source" .) "generated" }}
apiVersion: v1
kind: Secret
metadata:
{{- with .Values.alphaConfig.annotations }}
  annotations:
{{ tpl ( toYaml . ) $ | indent 4 }}
{{- end }}
  labels:
    app: {{ template "oauth2-proxy.name" . }}
    {{- include "oauth2-proxy.labels" . | indent 4 }}
  name: {{ include "oauth2-proxy.alpha-config.name" . }}
  namespace: {{ template "oauth2-proxy.namespace" $ }}
data:
  oauth2_proxy.yml: {{ include "oauth2-proxy.alpha-config" . | b64enc | quote }}
{{- end }}
