{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if $isDistributed }}
{{- include "loki.service" (dict "target" "compactor" "component" .Values.compactor "ctx" .) }}
{{- end }}
