{
 "title": "Sitespeed ##ENV##",
 "tags": [ "page" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "base", "label": "sitespeed_io", "query": "sitespeed_io" },
   { "name": "path", "query": "$base.*" },
   { "name": "group", "query": "$base.$path.pageSummary.*" },
   {
    "name": "page",
    "query": "$base.$path.pageSummary.$group.*"
   },
   {
    "name": "browser",
    "query": "$base.$path.pageSummary.$group.$page.*"
   },
   {
    "name": "connectivity",
    "query": "$base.$path.pageSummary.$group.$page.$browser.*"
   },
   { "name": "function", "query": "min, mean,median,p90,max" }
  ]
 },
 "panels": [
  {
   "title": "Visual Metrics",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LargestImage.$function, 10)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    }
   ]
  },
  {
   "title": "CPU [Chrome only]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.categories.*.median, 11)"
    }
   ]
  },
  { "title": "Visual Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "First visual change",
   "type": "singlestat",
   "description": "The first visual change is when something for the first time is painted within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function"
    }
   ]
  },
  {
   "title": "SpeedIndex",
   "type": "singlestat",
   "description": "The Speed Index is the average time at which visible parts of the page are displayed. It is expressed in milliseconds and dependent on size of the view port. It was created by Pat Meenan and you can checkout the full documentation [here](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index).",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function"
    }
   ]
  },
  {
   "title": "Perceptual SpeedIndex",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.PerceptualSpeedIndex.$function"
    }
   ]
  },
  {
   "title": "Visual Complete 85%",
   "type": "singlestat",
   "description": "The visual complete 85% is when 85% (or more) are finished within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualComplete85.$function"
    }
   ]
  },
  {
   "title": "Visual Complete 95%",
   "type": "singlestat",
   "description": "The visual complete 95% is when 95% (or more) are finished within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualComplete95.$function"
    }
   ]
  },
  {
   "title": "Last Visual Change",
   "type": "singlestat",
   "description": "The last visual change is when something for the last time is changing within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function"
    }
   ]
  },
  { "title": "Visual Metrics Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Avg last 24 hours",
   "type": "table",
   "description": "The moving average of the last 24 hours median values for the visual metrics.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '24h'), 10)"
    },
    {
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.PerceptualSpeedIndex.$function, '24h'), 10)"
    },
    {
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, '24h'), 10)"
    },
    {
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '24h'), 10)"
    },
    {
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualComplete85.$function, '24h'), 10)"
    }
   ]
  },
  {
   "title": "Relative to yesterday",
   "type": "table",
   "description": "Last 24 hours averages of median metrics compared to one day back in time. \n\nRed color background means a regression, green a positive change and yellow that the change is within the margin of error. You probably need to finetune the thresholds depending of how flakey your site is. Default threshold is +-10%.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), #A), #A), 10)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), '1d')), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), '1d')), 10)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '24h'), #B), #B), 10)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '24h'), '1d')), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '24h'), '1d')), 10)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.PerceptualSpeedIndex.$function, '24h'), #E), #E), 10)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.PerceptualSpeedIndex.$function, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.PerceptualSpeedIndex.$function, '24h'), '1d')), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.PerceptualSpeedIndex.$function, '24h'), '1d')), 10)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, '24h'), #G), #G), 10)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, '24h'), '1d')), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, '24h'), '1d')), 10)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '24h'), #I), #I), 10)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '24h'), '1d')), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '24h'), '1d')), 10)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualComplete85.$function, '24h'), #K), #K), 10)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualComplete85.$function, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualComplete85.$function, '24h'), '1d')), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualComplete85.$function, '24h'), '1d')), 10)"
    }
   ]
  },
  {
   "title": "Relative to last week",
   "type": "table",
   "description": "Last 24 hours averages of median metrics compared to seven days back in time. \n\nRed color background means a regression, green a positive change and yellow that the change is within the margin of error. You probably need to finetune the thresholds depending of how flakey your site is. Default threshold is +-10%.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), #A), #A), 10)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), '7d')), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), '7d')), 10)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '24h'), #B), #B), 10)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '24h'), '7d')), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '24h'), '7d')), 10)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, '24h'), #E), #E), 10)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, '24h'), '7d')), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, '24h'), '7d')), 10)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.PerceptualSpeedIndex.$function, '24h'), #G), #G), 10)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.PerceptualSpeedIndex.$function, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.PerceptualSpeedIndex.$function, '24h'), '7d')), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.PerceptualSpeedIndex.$function, '24h'), '7d')), 10)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '24h'), #I), #I), 10)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '24h'), '7d')), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '24h'), '7d')), 10)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualComplete85.$function, '24h'), #K), #K), 10)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualComplete85.$function, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualComplete85.$function, '24h'), '7d')), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualComplete85.$function, '24h'), '7d')), 10)"
    }
   ]
  },
  {
   "title": "Relative to last month",
   "type": "table",
   "description": "Last 24 hours averages of median metrics compared to one month back in time. \n\nRed color background means a regression, green a positive change and yellow that the change is within the margin of error. You probably need to finetune the thresholds depending of how flakey your site is. Default threshold is +-10%.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), #A), #A), 10)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), '30d')), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), '30d')), 10)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '24h'), #B), #B), 10)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '24h'), '30d')), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '24h'), '30d')), 10)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, '24h'), #E), #E), 10)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, '24h'), '30d')), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, '24h'), '30d')), 10)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.PerceptualSpeedIndex.$function, '24h'), #G), #G), 10)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.PerceptualSpeedIndex.$function, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.PerceptualSpeedIndex.$function, '24h'), '30d')), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.PerceptualSpeedIndex.$function, '24h'), '30d')), 10)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '24h'), #I), #I), 10)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '24h'), '30d')), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '24h'), '30d')), 10)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualComplete85.$function, '24h'), #K), #K), 10)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualComplete85.$function, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualComplete85.$function, '24h'), '30d')), timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualComplete85.$function, '24h'), '30d')), 10)"
    }
   ]
  },
  { "title": "Technical Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Fully loaded",
   "type": "singlestat",
   "description": "Fully loaded time when the last of all assets is downloaded on the page. It is calculated using the Resource Timing API where we use the last downloaded asset.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.requests"
    }
   ]
  },
  {
   "title": "Total transfer size",
   "type": "singlestat",
   "description": "The total transfer size over the wire (compressed size if your asset is compressed) of all assets on the page.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 26 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.transferSize"
    }
   ]
  },
  {
   "title": "Total content size",
   "type": "singlestat",
   "description": "The total size for all assets served for this page. This includes the uncompressed size for compressed text/css/html/js/font content.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 26 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentSize"
    }
   ]
  },
  {
   "title": "Document height",
   "type": "singlestat",
   "description": "The document height in pixels.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.documentHeight"
    }
   ]
  },
  {
   "title": "DOM Elements",
   "type": "singlestat",
   "description": "The total number of DOM elements on the page.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.domElements"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Iframes",
   "type": "singlestat",
   "description": "The total number of iframes used on the page.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.iframes"
    }
   ]
  },
  {
   "title": "DOM depth (avg)",
   "type": "singlestat",
   "description": "The average DOM depth of the page.",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.domDepth.avg"
    }
   ]
  },
  {
   "title": "DOM depth (max)",
   "type": "singlestat",
   "description": "The max depth of DOM elements on the page.",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.domDepth.max"
    }
   ]
  },
  {
   "title": "Local storage size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 31 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.localStorageSize"
    }
   ]
  },
  {
   "title": "Script tags",
   "type": "singlestat",
   "description": "In the DOM",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.scripts"
    }
   ]
  },
  {
   "title": "Cookies",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.cookieStats.$function"
    }
   ]
  },
  {
   "title": "Domains",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.totalDomains"
    }
   ]
  },
  { "title": "Coach score", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Coach Total Score",
   "type": "singlestat",
   "description": "The coach score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using best practices.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.score"
    }
   ]
  },
  {
   "title": "Performance Score",
   "type": "singlestat",
   "description": "The performance score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using performance best practices.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.performance.score"
    }
   ]
  },
  {
   "title": "Accessibility Score",
   "type": "singlestat",
   "description": "The accessibility score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using accessibility best practices.",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.accessibility.score"
    }
   ]
  },
  {
   "title": "Best Practice Score",
   "type": "singlestat",
   "description": "The best practice score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using web best practices.",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.bestpractice.score"
    }
   ]
  },
  {
   "title": "Privacy Score",
   "type": "singlestat",
   "description": "The privacy score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using user privacy best practices.",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.privacy.score"
    }
   ]
  },
  { "title": "History of Visual Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "History First Visual Change",
   "type": "graph",
   "description": "The history of First Visual Change (when something for the first time is painted within the current viewport) showing the current median value, the average median per day and the average median per week.",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 11)"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '24h', 'avg', true), 'Daily')"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '7d', 'avg', true), 'Weekly ')"
    }
   ]
  },
  {
   "title": "History Speed Index",
   "type": "graph",
   "description": "The history of [Speed Index](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index) showing the current median value, the average median per day and the average median per week.",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, 11)"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h', 'avg', true), 'Daily')"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '7d', 'avg', true), 'Weekly')"
    }
   ]
  },
  {
   "title": "History Perceptual Speed Index",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.PerceptualSpeedIndex.$function, 11)"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.PerceptualSpeedIndex.$function, '24h', 'avg', true), 'Daily')"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.PerceptualSpeedIndex.$function, '7d', 'avg', true), 'Weekly')"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "History Visual Complete 85%",
   "type": "graph",
   "description": "The history of Visual Complete 85% (when 85% (or more) if the page in the current viewport is rendered) showing the current median value, the average median per day and the average median per week.",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualComplete85.$function, 11)"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualComplete85.$function, '24h', 'avg', true), 'Daily')"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualComplete85.$function, '7d', 'avg', true), 'Weekly')"
    }
   ]
  },
  {
   "title": "History Last Visual Change",
   "type": "graph",
   "description": "The history of Last Visual Change (when something for the last time is changing within the current viewport) showing the current median value, the average median per day and the average median per week.",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, 11)"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, '24h', 'avg', true), 'Daily')"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, '7d', 'avg', true), 'Weekly')"
    }
   ]
  },
  {
   "title": "History Fully Loaded",
   "type": "graph",
   "description": "The history of Fully Loaded (when the last of all assets is downloaded on the page) showing the current median value, the average median per day and the average median per week.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, 11)"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '24h', 'avg', true), 'Daily')"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '7d', 'avg', true), 'Weekly')"
    }
   ]
  },
  { "title": "Size and requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Transfer Size",
   "type": "graph",
   "description": "The total transfer size by content type.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.*.transferSize, 9)"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "description": "The total number of requests by content type.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.*.requests, 9)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "None 200 response codes",
   "type": "graph",
   "description": "All requests that are not a 200 HTTP Status Code.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(exclude($base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.responseCodes.*, '200'), 9)"
    }
   ]
  },
  {
   "title": "Time spent in backend vs frontend % [$function]",
   "type": "graph",
   "description": "The max time spent in frontend vs backend time. \n\nThe backend time is the time it takes for the network and the server to generate and start sending the HTML. It is collected using the Navigation Timing API taking the responseStart minus navigationStart.\n\nThe frontend time is the time it takes for the browser to parse and create the page.  It is collected using the Navigation Timing API by taking the loadEventStart minus responseEnd.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(asPercent($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.backEndTime.$function, #C), 'Backend')",
     "targetFull": "alias(asPercent($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.backEndTime.$function, sumSeries($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.frontEndTime.max,$base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.backEndTime.max)), 'Backend')"
    },
    {
     "target": "alias(asPercent($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.frontEndTime.$function, #C), 'Frontend')",
     "targetFull": "alias(asPercent($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.frontEndTime.$function, sumSeries($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.frontEndTime.max,$base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.backEndTime.max)), 'Frontend')"
    }
   ]
  },
  {
   "title": "Browser technical timing metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 }
  },
  {
   "title": "DOMContentLoaded Time",
   "type": "graph",
   "description": "The time the browser takes to parse the document and execute deferred and parser-inserted scripts including the network time from the users location to your server.  It is collected using the Navigation Timing API by taking the domContentLoadedEventStart minus navigationStart.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.domContentLoadedTime.$function, 'Now')"
    },
    {
     "target": "alias(timeShift($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.domContentLoadedTime.$function, '7d'), 'One week back')"
    },
    {
     "target": "alias(summarize(#A, '1day', 'avg', true), \"daily avg\")"
    }
   ]
  },
  {
   "title": "Frontend Time",
   "type": "graph",
   "description": "The time it takes for the browser to parse and create the page.  It is collected using the Navigation Timing API by taking the loadEventStart minus responseEnd.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.frontEndTime.max)"
    },
    {
     "target": "aliasByMetric($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.frontEndTime.median)"
    },
    {
     "target": "aliasByMetric($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.frontEndTime.min)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "User timings",
   "type": "graph",
   "description": "All User Timing marks created on the page using the [User Timing API](https://www.w3.org/TR/user-timing/).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.userTimings.marks.*.$function, 12)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Navigation Timings",
   "type": "graph",
   "description": "[Navigation Timing API](https://www.w3.org/TR/navigation-timing/) metrics.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.*.$function, 11)"
    }
   ]
  },
  {
   "title": "1st vs 3rd party (enable by --firstParty REGEX)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 }
  },
  {
   "title": "First party transfer size",
   "type": "singlestat",
   "description": "The transfer size of all your first party responses.  \n\nThe first party content (content you serve your self ) are defined by the requests that  match the regexp you supply with the parameter *--firstParty*",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 124 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.firstParty.transferSize"
    }
   ]
  },
  {
   "title": "Third party transfer size",
   "type": "singlestat",
   "description": "The transfer size of all your third party responses.  \n\nThe third party content (content other companies/organizations serve like advertisement, social media buttons etc) are defined by the requests that doesn't match the regexp you supply with the parameter *--firstParty*",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 124 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.thirdParty.transferSize"
    }
   ]
  },
  {
   "title": "First party request",
   "type": "singlestat",
   "description": "The number of requests for all your first party responses.  \n\nThe first party content (content you serve your self ) are defined by the requests that match the regexp you supply with the parameter *--firstParty*",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 124 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.firstParty.requests"
    }
   ]
  },
  {
   "title": "Third party request",
   "type": "singlestat",
   "description": "The number of requests for all your third party responses.  \n\nThe third party content (content other companies/organizations serve like advertisement, social media buttons etc) are defined by the requests that doesn't match the regexp you supply with the parameter *--firstParty*",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 124 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.thirdParty.requests"
    }
   ]
  },
  {
   "title": "Chrome show transfer vs content size. Firefox only transfer size.",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 }
  },
  {
   "title": "Total transfer size",
   "type": "singlestat",
   "description": "The total size over the wire for all assets served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 128 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.transferSize"
    }
   ]
  },
  {
   "title": "Total content size",
   "type": "singlestat",
   "description": "The total size for all assets served for this page. This includes the uncompressed size for compressed text/css/html/js/font content.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 128 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentSize"
    }
   ]
  },
  {
   "title": "Total CSS transfer size",
   "type": "singlestat",
   "description": "The total size over the wire for all stylesheet assets served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 128 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.css.transferSize"
    }
   ]
  },
  {
   "title": "Total CSS content size",
   "type": "singlestat",
   "description": "The total size for stylesheets assets served for this page. This includes the uncompressed size of CSS responses.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 128 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.css.contentSize"
    }
   ]
  },
  {
   "title": "Total JS transfer size",
   "type": "singlestat",
   "description": "The total size over the wire for all Javascript assets served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 128 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.javascript.transferSize"
    }
   ]
  },
  {
   "title": "Total JS content size",
   "type": "singlestat",
   "description": "The total size for Javascripts assets served for this page. This includes the uncompressed size of JS responses.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 128 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.javascript.contentSize"
    }
   ]
  },
  {
   "title": "Total HTML transfer size",
   "type": "singlestat",
   "description": "The total size over the wire for all HTML served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 131 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.html.transferSize"
    }
   ]
  },
  {
   "title": "Total HTML content size",
   "type": "singlestat",
   "description": "The total size for HTML served for this page. This includes the uncompressed size of HTML.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 131 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.html.contentSize"
    }
   ]
  },
  {
   "title": "Total font transfer size",
   "type": "singlestat",
   "description": "The total size over the wire for all font(s) served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 131 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.font.transferSize"
    }
   ]
  },
  {
   "title": "Total font content size",
   "type": "singlestat",
   "description": "The total size for font(s) served for this page. This includes the uncompressed size.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 131 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.font.contentSize"
    }
   ]
  },
  {
   "title": "Total image size",
   "type": "singlestat",
   "description": "The total size for images served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 131 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.image.contentSize"
    }
   ]
  },
  {
   "title": "Total SVG transfer size",
   "type": "singlestat",
   "description": "The total size over the wire for all SVG(s) served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 131 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.svg.transferSize"
    }
   ]
  }
 ]
}