{{- $isMonolithic := eq (include "loki.deployment.isMonolithic" .) "true" -}}
{{- $usingObjectStorage := eq (include "loki.isUsingObjectStorage" .) "true" }}
{{- if and $isMonolithic $usingObjectStorage }}
{{- $targetName := include "loki.resourceName" (dict "ctx" .) -}}
{{- include "loki.keda" (dict "target" "single-binary" "component" .Values.singleBinary "ctx" . "targetName" $targetName) }}
{{- end }}
