repoName: otomi/values.git
branchName: main

image:
  repository: linode/apl-http-git-server
  tag: v0.1.0
  pullPolicy: IfNotPresent

initImage:
  git:
    repository: alpine/git
    tag: v2.52.0
    pullPolicy: IfNotPresent
  debian:
    repository: ubuntu
    tag: "24.04"
    pullPolicy: IfNotPresent

persistence:
  size: 256Mi
  storageClass: ""

auth:
  username: otomi-admin
  password: ""

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

service:
  port: 80
