{{- $dot := . }}
{{- $v := .Values }}
{{- range $gateway := $v.gateways }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-{{ $gateway.name }}-options
  labels:
    {{- include "kubernetes-gateways.labels" $dot | nindent 4 }}
data:
  {{- with $gateway.hpa }}
  horizontalPodAutoscaler: |
    spec:
      minReplicas: {{ .minReplicas | default 2 }}
      maxReplicas: {{ .maxReplicas | default 2 }}
      {{- with .metrics }}
      metrics:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
  {{- end }}
  {{- else }}
  {}
{{- end }}
