{{- $v := .Values }}
{{- range $gateway := .Values.gateways }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $gateway.name }}
  {{- with $gateway.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ $gateway.class | default $v.defaultGatewayClass }}
  {{- with $gateway.loadBalancerIP }}
  addresses:
    - value: {{ . | quote }}
      type: IPAddress
  {{- end }}
  {{- with $gateway.serviceAnnotations }}
  infrastructure:
    annotations:
      {{- . | toYaml | nindent 6 }}
  {{- end }}
  listeners:
    {{- $gateway.listeners | toYaml | nindent 4 }}
{{- end }}
