{{- $dot := . }}
{{- $v := .Values }}
{{- range $gateway := $v.gateways }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $gateway.name }}
  {{- with $gateway.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kubernetes-gateways.labels" $dot | nindent 4 }}
spec:
  gatewayClassName: {{ $gateway.class | default $v.defaultGatewayClass }}
  {{- with $gateway.loadBalancerIP }}
  addresses:
    - value: {{ . | quote }}
      type: IPAddress
  {{- end }}
  infrastructure:
    {{- with $gateway.serviceAnnotations }}
    annotations:
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    parametersRef:
      group: ""
      kind: ConfigMap
      name: gateway-{{ $gateway.name }}-options
  {{- with $gateway.allowedListeners }}
  allowedListeners:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  listeners:
    {{- $gateway.listeners | toYaml | nindent 4 }}
{{- end }}
