{{- if and .Values.imageRenderer.enabled .Values.imageRenderer.service.enabled (not .Values.imageRenderer.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.imageRenderer.fullname" . }}-image-renderer
  namespace: {{ include "grafana.namespace" . }}
  labels:
    {{- include "grafana.imageRenderer.labels" . | nindent 4 }}
    {{- with .Values.imageRenderer.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.imageRenderer.service.annotations }}
  annotations:
    {{- tpl (toYaml . | nindent 4) $ }}
  {{- end }}
data:
  {{- if .Values.imageRenderer.token }}
  token: {{ .Values.imageRenderer.token | b64enc | quote }}
  {{- else }}
  token: {{ include "grafana.imageRenderer.token" . }}
  {{- end }}
{{- end }}
