apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otomi-api.fullname" . }}
  labels:
{{ include "otomi-api.labels" . | indent 4 }}
data:
{{- with .Values.secrets }}
{{- range $key, $val := . }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- else }}
  {}
{{- end }}
