{{- if .Values.server.httproute.enabled -}}
{{- $fullName := include "argo-cd.server.fullname" . -}}
{{- $insecure := index .Values.configs.params "server.insecure" | toString -}}
{{- $servicePort := eq $insecure "true" | ternary .Values.server.service.servicePortHttp .Values.server.service.servicePortHttps -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ include  "argo-cd.namespace" . }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
    {{- with .Values.server.httproute.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.server.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- if .Values.server.httproute.parentRefs }}
    {{- toYaml .Values.server.httproute.parentRefs | nindent 4 }}
    {{- else if .Values.server.listenerset.enabled }}
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: {{ $fullName }}
      namespace: {{ include "argo-cd.namespace" . }}
      sectionName: {{ .Values.server.listenerset.listenerName }}
    {{- end }}
  {{- if .Values.server.httproute.hostnames }}
  hostnames:
    {{- toYaml .Values.server.httproute.hostnames | nindent 4 }}
  {{- else if .Values.server.listenerset.enabled }}
  hostnames:
    - {{ tpl (.Values.server.listenerset.hostname | default .Values.global.domain) $ | quote }}
  {{- end }}
  rules:
  {{- range .Values.server.httproute.rules }}
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ $fullName }}
          port: {{ $servicePort }}
          weight: 1
    {{- with .filters }}
      filters:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .matches }}
      matches:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .timeouts }}
      timeouts:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end }}
{{- end }}
