{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if $isDistributed }}
{{- include "loki.hpa" (dict "target" "querier" "component" .Values.querier "ctx" . "kind" "Deployment") }}
{{- end }}
