{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if $isDistributed -}}
{{- include "loki.service" (dict "target" "querier" "component" .Values.querier "ctx" .) }}
{{- end -}}
