{{- $v := .Values}}
{{- if $v.apps.tekton.enabled }}
{{- $t := $v.teamApps.tekton }}
# use nonroot linux/amd64 image
# current tag: v0.112.0-nonroot
{{- $imageDigest := "sha256:f666817cbac2bee23cc78a433b4e739456ce221438c0c8ac6bdeaf7bc1a73839" }}
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: grype
  annotations:
    # Use ArgoCD sync wave annotation to ensure tasks are created first
    argocd.argoproj.io/sync-wave: "-5"
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Security
    tekton.dev/tags: CLI, grype
    tekton.dev/displayName: "grype"
    tekton.dev/platforms: "linux/amd64"
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  stepTemplate:
    computeResources:
      {{- $t.resources.grypeTask | toYaml | nindent 6 }}
  description: >-
    A vulnerability scanner for container images and filesystems.
    Works with Syft, the powerful SBOM (software bill of materials) tool for container images and filesystems.
  workspaces:
    - name: source-dir
      optional: true
  params:
    - name: ARGS
      description: The Arguments to be passed to Grype command.
      type: array
    - name: GRYPE_IMAGE
      {{- with $v.linodeLkeImageRepository }}
      default: "{{ . }}/docker/anchore/grype@{{ $imageDigest }}"
      {{- else }}
      default: "docker.io/anchore/grype@{{ $imageDigest }}"
      {{- end }}
      description: Grype image to be used
      type: string
  steps:
    - name: grype
      computeResources: {}
      image: $(params.GRYPE_IMAGE)
      workingDir: $(workspaces.source-dir.path)
      args:
        - "$(params.ARGS)"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - "ALL"
        runAsUser: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: cache-dir
          mountPath: /.cache

  volumes:
    - name: cache-dir
      emptyDir: {}

{{- end }}
