{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if $isDistributed }}
{{- include "loki.serviceAccount" (dict "target" "pattern-ingester" "component" .Values.patternIngester "ctx" .) }}
{{- end -}}
