{{- $git := .Values.otomi.git | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: apl-git-config
  namespace: apl-secrets
type: Opaque
stringData:
  {{- with $git.repoUrl }}
  repoUrl: {{ . | quote }}
  {{- end }}
  branch: {{ $git.branch | quote }}
  {{- with $git.email }}
  email: {{ . | quote }}
  {{- end }}
  {{- with $git.username }}
  username: {{ . | quote }}
  {{- end }}
  {{- if $git.password }}
  password: {{ . | quote }}
  {{- end }}
