{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if $isDistributed }}
{{- include "loki.pdb" (dict "target" "distributor" "component" .Values.distributor "ctx" .) }}
{{- end }}
