{
 "title": "Azure Redis",
 "tags": [
  "azure",
  "redis"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Subscriptions",
    "label": "Subscriptions",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "ResourceGroup", "label": "Resource Group", "query": "ResourceGroups()" },
   {
    "name": "ResourceName",
    "query": "ResourceNames($ResourceGroup,Microsoft.Cache/Redis)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "percentProcessorTime",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    }
   ]
  },
  {
   "title": "Last Memory usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "usedmemorypercentage",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    }
   ]
  },
  {
   "title": "Last Server Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "serverLoad",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    }
   ]
  },
  {
   "title": "Cache latency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 1 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "cacheLatency",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    }
   ]
  },
  {
   "title": "Errors / Min",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" },
       { "text": "ErrorType", "value": "ErrorType" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "errors",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "connectedclients",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Cache Hits vs Cache Miss",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Cache Hits",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "cachehits",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    },
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Cache Miss",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "cachemisses",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ops", "label": "Ops / Sec" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Total Operations",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "totalcommandsprocessed",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT5M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    },
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "Operations / sec",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "operationsPerSecond",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT5M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    }
   ]
  },
  {
   "title": "Cache Read vs Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "Cache Write",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "cacheWrite",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    },
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "Cache Read",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "cacheRead",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "{{dimensionvalue}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "ErrorType",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" },
       { "text": "ErrorType", "value": "ErrorType" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "errors",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    },
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "Total Errors",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" },
       { "text": "ErrorType", "value": "ErrorType" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "errors",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    }
   ]
  },
  {
   "title": "Cache Latency & Connected Clients",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "µs", "label": "Cache Latency" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "Connected Clients",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "connectedclients",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "Cache latency",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "cacheLatency",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Gets & Sets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Gets",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "getcommands",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Sets",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "setcommands",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Keys",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "Total Keys",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "totalkeys",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    },
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Evicted Keys",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "evictedkeys",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    },
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Expired Keys",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "expiredkeys",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    }
   ]
  },
  {
   "title": "CPU, Memory & Server Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "percentProcessorTime",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    },
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "usedmemorypercentage",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    },
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "ShardId", "value": "ShardId" }
      ],
      "metricDefinition": "Microsoft.Cache/Redis",
      "metricName": "serverLoad",
      "metricNamespace": "Microsoft.Cache/Redis",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "2e8c6d42-375b-4fa5-9cea-bb3390b86d8a"
    }
   ]
  }
 ]
}