apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-server-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "git-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ if eq . "" }}""{{ else }}{{ . }}{{ end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
