{{- if .Values.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: git-server-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "git-server.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.auth.username | b64enc }}
  password: {{ .Values.auth.password | b64enc }}
{{- end }}
