{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if $isDistributed }}
{{- include "loki.service" (dict "target" "query-scheduler" "component" .Values.queryScheduler "ctx" .) }}
{{- end }}
