{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if $isDistributed }}
{{- include "loki.service" (dict "target" "index-gateway" "component" .Values.indexGateway "ctx" .) }}
{{- end }}
