{
 "title": "Loki2.0 Global Metrics",
 "description": "Loki metrics via 2.0",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"left dashboard-header\">\n   <img src=\"https://marketplace-assets.digitalocean.com/logos/loki-logo.svg\" style=\"height:29px;\"/>\n  <span>Loki Global Metrics</span>\n</div>"
   },
   "targets": [
    { "expr": "loki_build_info" }
   ]
  },
  {
   "title": "Store Series Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(loki_store_series_total)" }
   ]
  },
  {
   "title": "Store Chunks Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_ingester_chunk_stored_bytes_total)"
    }
   ]
  },
  {
   "title": "Panic ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "loki_panic_total" }
   ]
  },
  {
   "title": "Loki Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "loki_build_info" }
   ]
  },
  {
   "title": "API Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket[5m])) by (le,route))",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "LogQL Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "LogQL  Processed bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_bytes_processed_per_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Distributor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Received Lines / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (tenant) (rate(loki_distributor_lines_received_total[5m]))",
     "legendFormat": "distributor / {{ tenant}}"
    }
   ]
  },
  {
   "title": "Distributor  Received bytes / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total[5m])) by (tenant)",
     "legendFormat": "distributor / {{tenant}}"
    }
   ]
  },
  {
   "title": "batch appends sent to ingesters / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki_distributor_ingester_appends_total[5m])",
     "legendFormat": "successed"
    },
    {
     "expr": "loki_distributor_ingester_append_failures_total",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Store Series / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(loki_store_series_total[5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Ingster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Blocks / Chunk",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_blocks_per_chunk_bucket[5m])) by (le))",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Chunk Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket[5m])) by (le))",
     "legendFormat": "chunk size"
    }
   ]
  },
  {
   "title": "Chunk Age",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_age_seconds_bucket[5m])) by (le))",
     "legendFormat": "ages"
    }
   ]
  },
  {
   "title": "Chunk Compression Ratios",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket[5m])) by (le))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Chunk Encode Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_encode_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "durations."
    }
   ]
  },
  {
   "title": "Lines / Chunk",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_entries_bucket[5m])) by (le))",
     "legendFormat": "lines"
    }
   ]
  },
  {
   "title": "Chunk Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki_ingester_chunks_created_total[5m])",
     "legendFormat": "create"
    },
    {
     "expr": "sum by (reason) (rate(loki_ingester_chunks_flushed_total[5m]))",
     "legendFormat": "flush / {{ reason }}"
    },
    {
     "expr": "sum by (fake) (rate(loki_ingester_chunks_stored_total[5m]))",
     "legendFormat": "stored"
    },
    {}
   ]
  },
  {
   "title": "Chunks in Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "loki_ingester_memory_chunks", "legendFormat": "chunks" }
   ]
  },
  {
   "title": "Strams Stats",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki_ingester_streams_created_total[5m])",
     "legendFormat": "create"
    },
    {
     "expr": "rate(loki_ingester_streams_removed_total[5m])",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "Chunks in Streams",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (tenan) (loki_ingester_memory_streams)",
     "legendFormat": "streams"
    }
   ]
  }
 ]
}