{{- if .Values.ingress.enabled -}}
{{- $fullName := include "headlamp.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ include "headlamp.namespace" . }}
  labels:
    {{- include "headlamp.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }} 
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .type }}
            backend:
              service:
                {{- $svc := dict }}
                {{- if and .backend .backend.service }}
                  {{- $svc = .backend.service }}
                {{- end }}
                {{- if $svc.name }}
                name: {{ tpl $svc.name $ | trim | quote }}
                {{- else }}
                name: {{ $fullName }}
                {{- end }}
                port:
                  {{- $port := $svc.port | default dict }}
                  {{- if $port.number }}
                  number: {{ $port.number }}
                  {{- else if $port.name }}
                  name: {{ $port.name }}
                  {{- else }}
                  number: {{ $svcPort }}
                  {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
