{{- $v := .Values }}
{{- $defaultIngressClass := $v.ingress.platformClass.className }}
{{- range $s := $v.services }}
{{- $isCoreService := $s.isCore | default false }}
{{- if not (and $isCoreService (eq $v.teamId "admin")) }}
{{- $tlsPass := $s.tlsPass | default false }}
{{- $backendPort := ternary 443 80 $tlsPass }}
{{- $isKnativeService := dig "ksvc" "predeployed" false $s }}
{{- $teamSuffix := ternary $v.teamId (print "team-" $v.teamId) $isKnativeService }}
{{- $serviceName := print $s.name "-" $teamSuffix }}
---
{{- if $tlsPass }}
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: TLSRoute
{{- else }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
{{- end }}
metadata:
  {{- with $v.httpRouteAnnotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  name: {{ $serviceName }}
spec:
  hostnames:
    - {{ $serviceName }}.{{ $v.domain }}
    {{- if $s.useCname }}
    - {{ $s.cname.domain }}
    {{- end }}
  parentRefs:
    - name: {{ $s.ingressClassName | default $defaultIngressClass }}
      namespace: istio-system
  rules:
    - backendRefs:
        - name: {{ $v.ingressPublicGatewayName }}
          namespace: istio-system
          port: {{ $backendPort }}
      matches:
      {{- if and $s.paths (gt (len $s.paths) 0) }}
      {{- range $path := $s.paths }}
        - path:
            type: PathPrefix
            value: {{ $path }}
      {{- end }}
      {{- else }}
        - path:
            type: PathPrefix
            value: /
      {{- end }}
        - filters:
            - type: RequestRedirect
              requestRedirect:
                scheme: https
                statusCode: 301
{{- if and $s.useCname $s.cname.tlsSecretName }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: {{ $serviceName }}-tls-secret
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: istio-system
  to:
    - group: ""
      kind: Secret
      name: {{ $s.cname.tlsSecretName }}
{{- end }}{{- /* useCname and tlsSecretName */}}
{{- end }}{{- /* $isCoreService of admin */}}
{{- end }}{{- /* range services */}}
