{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if (and $isDistributed (gt (int .Values.bloomPlanner.replicas) 0)) -}}
{{- include "loki.service" (dict "target" "bloom-planner" "component" .Values.bloomPlanner "ctx" .) }}
{{- end -}}
