FROM ubuntu:latest

RUN apt update && apt upgrade -y && apt install -y ttyd jq curl vim wget tmux

RUN curl -LO https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_amd64.tar.gz && tar zxf k9s_Linux_amd64.tar.gz -C /usr/local/bin/ && rm k9s_Linux_amd64.tar.gz

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && rm kubectl

RUN wget "https://github.com/vmware-tanzu/velero/releases/download/v1.11.0/velero-v1.11.0-linux-amd64.tar.gz" && tar zxvf velero-v1.11.0-linux-amd64.tar.gz && mv velero-v1.11.0-linux-amd64/velero /usr/local/bin/ && rm -rf velero-v1.11.0-linux-amd64*

RUN curl -LO https://github.com/tektoncd/cli/releases/download/v0.31.1/tkn_0.31.1_Linux_x86_64.tar.gz && tar zxvf tkn_0.31.1_Linux_x86_64.tar.gz -C /usr/local/bin/ tkn

RUN addgroup --gid 1000 user && adduser --uid 1000 --gid 1000 --disabled-password --gecos "" user && echo 'user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

USER user

RUN touch ~/.bashrc && echo 'source <(kubectl completion bash)' >>~/.bashrc && echo 'alias k=kubectl' >>~/.bashrc && echo 'complete -o default -F __start_kubectl k' >>~/.bashrc && mkdir ~/.kube

CMD ["ttyd", "-p", "8080", "tmux", "new", "-A"]