#!/bin/sh

. "$(dirname "$0")/_/husky.sh"
. .env

if [ "${ENABLE_HELM_DOCS:-true}" = "true" ]; then 
  docker run --rm --volume "$PWD/chart/otomi:/helm-docs" -u $(id -u) jnorwood/helm-docs:latest
  git add $PWD/chart/otomi/README.md
fi