#!/bin/sh

# It takes one to three parameters.
# The first is the name of the file that contains the commit log message.
# The second is the source of the commit message, and can be:
# - message (if a -m or -F option was given);
# - template (if a -t option was given or the configuration option commit.template is set);
# - merge (if the commit is a merge or a .git/MERGE_MSG file exists);
# - squash (if a .git/SQUASH_MSG file exists); or
# - commit, followed by a commit object name (if a -c, -C or --amend option was given).

# If the exit status is non-zero, git commit will abort.

# Run interactive commitizen if git message is not set
[ -z "$2" ] && exec </dev/tty && npx cz --hook || true
