{{- $isSimpleScalable := eq (include "loki.deployment.isScalable" .) "true" -}}
{{- if $isSimpleScalable }}
{{- include "loki.component" (dict "ctx" . "component" .Values.write "target" "write") }}
{{- end }}
