name: 'coverage'
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '*.json'
      - '*.js'
      - '*.ts'

jobs:
  coverage:
    continue-on-error: true
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v7

      - name: Install Node
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install
          nvm use
          node -v
          npm install

      - name: Compare Coverage
        continue-on-error: true
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm run test:ts
          annotations: none
