{
 "title": "Policy compliance",
 "description": "Dashboard to view kyverno published metrics",
 "tags": [
  "kyverno",
  "security"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Summary of security policies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Compliant",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(resource_namespace) (kyverno_policy_results_total{rule_result=\"pass\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skipped",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(resource_namespace) (kyverno_policy_results_total{rule_result=\"skip\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WARNING",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(resource_namespace) (kyverno_policy_results_total{rule_result=\"warn\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not Compliant",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(resource_namespace) (kyverno_policy_results_total{rule_result=\"fail\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UNKNOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(resource_namespace) (kyverno_policy_results_total{rule_result=\"error\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All non-compliant security policies by policy name",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kyverno_policy_results_total{rule_result=\"fail\"}) by (policy_name)",
     "legendFormat": "{{severity}}"
    }
   ]
  }
 ]
}